# Generated by Django 3.1.7 on 2021-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='conf_attended',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='education',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='projects',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='publication',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='sub_dealt',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='work_exp',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='workshops_attended',
            field=models.TextField(max_length=500),
        ),
    ]
