# Generated by Django 3.1.7 on 2021-04-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0005_timetablenacedemics_is_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifiation',
            new_name='Notification',
        ),
    ]
