# Generated by Django 3.2 on 2021-05-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0007_auto_20210502_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
