# Generated by Django 3.2 on 2021-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0008_alter_publication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='coordinators',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='covinor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
