# Generated by Django 3.2 on 2021-05-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0010_alter_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categories',
            new_name='category',
        ),
    ]
