# Generated by Django 3.2 on 2021-05-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0014_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(),
        ),
    ]
