# Generated by Django 3.2 on 2021-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0015_alter_slide_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
