# Generated by Django 3.2 on 2021-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0019_auto_20210508_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
