# Generated by Django 3.2 on 2021-05-18 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0022_auto_20210510_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=7)),
                ('linked_in', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('call_letter', models.FileField(upload_to='placements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img', 'doc', 'pdf', 'ppt'])])),
                ('start_date', models.DateField()),
                ('request', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dept_site.job')),
                ('end_date', models.DateField()),
            ],
            bases=('dept_site.job',),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dept_site.job')),
                ('initial_package', models.IntegerField()),
            ],
            bases=('dept_site.job',),
        ),
    ]
