# Generated by Django 3.2 on 2021-05-18 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0023_internship_job_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('logo', models.ImageField(upload_to='slides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img'])])),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('colab_type', models.CharField(choices=[('Academic Partnerships', 'Academic Partnerships'), ('Industries Interactions', 'Industries Interactions'), ('Professional Cooperations', 'Professional Cooperations'), ('Research Partnerships', 'Research Partnerships'), ('Others', 'Others')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
