# Generated by Django 3.2 on 2021-05-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0025_job_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='end_date',
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_role',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placement',
            name='initial_package',
            field=models.FloatField(),
        ),
    ]
