# Generated by Django 3.2 on 2021-05-19 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0026_auto_20210518_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phn_no', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=None, upload_to='job_students', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default=None, upload_to='staff_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='call_letter',
            field=models.FileField(upload_to='jobs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img', 'doc', 'pdf', 'ppt'])]),
        ),
    ]
