# Generated by Django 3.2.3 on 2021-05-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0029_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='dept_site.news'),
        ),
    ]
