# Generated by Django 3.2.3 on 2021-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_site', '0030_alter_file_f_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='gender',
        ),
        migrations.AlterField(
            model_name='file',
            name='a_file',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
    ]
